// <auto-generated />
namespace Repository_and_Unit_of_Work_Patterns.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class columnFirstName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnFirstName));
        
        string IMigrationMetadata.Id
        {
            get { return "201704131403208_columnFirstName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
